Algoritmo ELECCIONDEPANEL
	Escribir "INGRESE SU NOMBRE DE USUARIO"
	Leer USUARIO
	Si USUARIO="EXISTE" Entonces
	
	SiNo
		Escribir RSGISTRAR NUEVO USUARIO
		Leer USUARIONUEVO
	FinSi
	Leer PANEL
	Segun PANEL Hacer
		BIBLIOTECA:
			Escribir "IR A BIBLIOTECA"
		EDITOR DE IMAGENES:
			Escribir "IR AL EDITOR DE IMAGENES"
		CONVERTIDOR LOTES:
			Escribir "IR AL CONVERTIDOR DE LOTES"
	FinSegun
FinAlgoritmo
